name: CI

on: [push, pull_request]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: node-version: '18'
      - run: npm ci
      - run: npm run build
      - name: Iniciar servidor
        run: npx serve dist -l 5500 &
      - run: npx playwright install --with-deps
      - run: npm run test:e2e
